#Generated by libmep version 2023.3.29.0-beta

import math

def mepx(x, outputs):
  prg = [0] * 100
  prg[0] = 0.428517
  prg[1] = math.pow(prg[0], prg[0])
  prg[2] = x[11]
  prg[3] = 0.376183
  prg[4] = 0.376183
  prg[5] = math.sin(prg[1])
  prg[6] = x[3]
  prg[7] = x[3]
  prg[8] = x[2]
  prg[9] = x[6]
  prg[10] = 0.410539
  prg[11] = math.sin(prg[7])
  prg[12] = x[12]
  prg[13] = x[11]
  prg[14] = x[8]
  prg[15] = x[12]
  prg[16] = math.pow(prg[0], prg[10])
  prg[17] = prg[12] + prg[1]
  prg[18] = x[11]
  prg[19] = math.exp(prg[0])
  prg[20] = x[13]
  prg[21] = math.sin(prg[16])
  prg[22] = x[3]
  prg[23] = math.sin(prg[0])
  prg[24] = prg[21] - prg[21]
  prg[25] = x[1]
  prg[26] = x[4]
  prg[27] = x[2]
  prg[28] = x[10]
  prg[29] = x[0]
  prg[30] = x[2]
  prg[31] = prg[20] + prg[12]
  prg[32] = prg[7] * prg[22]
  prg[33] = x[9]
  prg[34] = x[12]
  prg[35] = x[4]
  prg[36] = x[12]
  prg[37] = prg[20] - prg[27]
  prg[38] = x[5]
  prg[39] = x[8]
  prg[40] = x[6]
  prg[41] = x[2]
  prg[42] = x[3]
  prg[43] = x[13]
  prg[44] = prg[3] - prg[4]
  prg[45] = prg[15] if prg[10] < 0 else prg[41] # ifalzbc
  prg[46] = x[12]
  prg[47] = prg[36] if prg[23] < 0 else prg[34] # ifalzbc
  prg[48] = prg[38] if prg[37] < 0 else prg[3] # ifalzbc
  prg[49] = x[1]
  prg[50] = x[11]
  prg[51] = math.pow(prg[15], prg[5])
  prg[52] = x[9]
  prg[53] = x[2]
  prg[54] = 0.428517
  prg[55] = x[13]
  prg[56] = x[12]
  prg[57] = x[5]
  prg[58] = x[5]
  prg[59] = prg[51] if prg[49] < prg[20] else prg[38] # ifalbcd
  prg[60] = 0.376183
  prg[61] = x[1]
  prg[62] = x[12]
  prg[63] = x[9]
  prg[64] = math.sin(prg[5])
  prg[65] = prg[28] - prg[36]
  prg[66] = prg[32] * prg[6]
  prg[67] = 0.465606
  prg[68] = 0.376183
  prg[69] = x[4]
  prg[70] = prg[44] if prg[58] < 0 else prg[32] # ifalzbc
  prg[71] = prg[44] if prg[61] < prg[34] else prg[19] # ifalbcd
  prg[72] = x[11]
  prg[73] = prg[48] * prg[59]
  prg[74] = prg[46] - prg[20]
  prg[75] = prg[36] - prg[43]
  prg[76] = prg[2] + prg[42]
  prg[77] = x[12]
  prg[78] = prg[19] * prg[11]
  prg[79] = prg[31] + prg[53]
  prg[80] = prg[3] + prg[73]
  prg[81] = x[8]
  prg[82] = x[2]
  prg[83] = x[10]
  prg[84] = prg[60] - prg[21]
  prg[85] = x[8]
  prg[86] = x[9]
  prg[87] = 0.410539
  prg[88] = x[7]
  prg[89] = x[2]
  prg[90] = x[3]
  prg[91] = x[5]
  prg[92] = prg[53] - prg[30]
  prg[93] = x[11]
  prg[94] = x[10]
  prg[95] = prg[16] if prg[4] < prg[64] else prg[32] # ifalbcd
  prg[96] = 0.465606
  prg[97] = x[1]
  prg[98] = prg[64] + prg[92]
  prg[99] = x[3]

  outputs[0] = prg[80]


#example of utilization ...

x = [
1.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.833333, -0.826087, 1.000000, 0.819000, 0.736000, 0.009434, 0.272143]

outputs = [0]

mepx(x, outputs)

print(outputs[0])
